# Generated by Django 4.2.2 on 2023-07-02 14:09

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MenuCategory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("category", models.CharField(max_length=30)),
            ],
            bases=(models.Model, api.models.BasePermissions),
        ),
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("restaurant_name", models.CharField(max_length=35)),
                ("short_description", models.CharField(max_length=60)),
                ("restaurant_image", models.ImageField(upload_to="")),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
            ],
            bases=(models.Model, api.models.BasePermissions),
        ),
        migrations.CreateModel(
            name="FeaturedMenuCategory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "featured",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.menucategory",
                    ),
                ),
            ],
            bases=(models.Model, api.models.BasePermissions),
        ),
        migrations.CreateModel(
            name="Dish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dish_name", models.CharField(max_length=30)),
                ("dish_image", models.ImageField(upload_to="")),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.restaurant"
                    ),
                ),
            ],
            bases=(models.Model, api.models.BasePermissions),
        ),
    ]
