# Generated by Django 4.2.2 on 2023-07-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dish",
            name="category",
            field=models.ManyToManyField(to="api.menucategory"),
        ),
    ]
